# Libraries

In [1]:
import pandas as pd                         
import scipy as sp                          
import numpy as np                          

&nbsp;

&nbsp;

# Question 1

In [2]:
np.__version__

'1.21.5'

&nbsp;

&nbsp;

# Load data

In [8]:
df = pd.read_csv("../ML/data.csv", sep=",")

&nbsp;

&nbsp;

# Question 2

In [9]:
df.shape

(11914, 16)

&nbsp;

&nbsp;

# Question 3

In [12]:
df.Make.value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

&nbsp;

&nbsp;

# Question 4

In [14]:
audi = df[df['Make'] == "Audi"]

In [18]:
audi.Model.nunique()

34

&nbsp;

&nbsp;

# Question 5

In [75]:
for column in df:
    print(df[column].isna().sum(), end=",", flush=True)

0,0,0,3,69,0,0,0,6,3742,0,0,0,0,0,0,0,

In [49]:
nan_df = {"cols_names" : df.columns.values,
          
          "cols_na_vals" : [0,0,0,3,69,30,0,0,6,3742,0,0,0,0,0,0]}

df_nan = pd.DataFrame(nan_df,
                      columns = ["cols_names", "cols_na_vals"]) 

In [50]:
df_nan

cols_names  cols_na_vals
0                Make             0
1               Model             0
2                Year             0
3    Engine Fuel Type             3
4           Engine HP            69
5    Engine Cylinders            30
6   Transmission Type             0
7       Driven_Wheels             0
8     Number of Doors             6
9     Market Category          3742
10       Vehicle Size             0
11      Vehicle Style             0
12        highway MPG             0
13           city mpg             0
14         Popularity             0
15               MSRP             0

&nbsp;

&nbsp;

# Question 6

In [60]:
df["Engine Cylinders"].describe()

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [65]:
df['Engine Cylinders Filled'] = df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode()[0])

In [66]:
df['Engine Cylinders Filled'].describe()

count    11914.000000
mean         5.624727
std          1.780189
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders Filled, dtype: float64

&nbsp;

&nbsp;

# Question 7

In [82]:
lotus = df[df['Make'] == "Lotus"]

In [87]:
lotus = lotus[["Engine HP", "Engine Cylinders"]].drop_duplicates()

In [88]:
lotus

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [105]:
X = lotus.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [106]:
XTX = np.matmul(X.T,X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [107]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [100]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [108]:
t = (np.matmul(inv_XTX,X.T))
w = np.dot(t, y)
w

array([  4.59494481, -63.56432501])